// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyWvJN8E2lC-adsS7g6faMjz8nUjA1gM',
    appId: '1:127755007959:web:fe92fa513bb51bd2b5fd92',
    messagingSenderId: '127755007959',
    projectId: 'proje1-44b92',
    authDomain: 'proje1-44b92.firebaseapp.com',
    databaseURL: 'https://proje1-44b92-default-rtdb.firebaseio.com',
    storageBucket: 'proje1-44b92.appspot.com',
    measurementId: 'G-Y01RBS1FG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyYt_W3559_0oqDcuTcA_xV7Gus6d938c',
    appId: '1:127755007959:android:791db1e47b33699bb5fd92',
    messagingSenderId: '127755007959',
    projectId: 'proje1-44b92',
    databaseURL: 'https://proje1-44b92-default-rtdb.firebaseio.com',
    storageBucket: 'proje1-44b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwvjoj7tKY1iYd9Y8n6fCqCw52o4PLA6g',
    appId: '1:127755007959:ios:eaee1513bfb6fc17b5fd92',
    messagingSenderId: '127755007959',
    projectId: 'proje1-44b92',
    databaseURL: 'https://proje1-44b92-default-rtdb.firebaseio.com',
    storageBucket: 'proje1-44b92.appspot.com',
    iosClientId: '127755007959-gfm1r0sb5ge3todd5dmn7er121t7297e.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwvjoj7tKY1iYd9Y8n6fCqCw52o4PLA6g',
    appId: '1:127755007959:ios:eaee1513bfb6fc17b5fd92',
    messagingSenderId: '127755007959',
    projectId: 'proje1-44b92',
    databaseURL: 'https://proje1-44b92-default-rtdb.firebaseio.com',
    storageBucket: 'proje1-44b92.appspot.com',
    iosClientId: '127755007959-gfm1r0sb5ge3todd5dmn7er121t7297e.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje1',
  );
}
